# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

terminal_files2 = {
  "gfx2DGlue.h",
  "gfxContext.h",
  "GMPCrashHelper.h",
  "ImageContainer.h",
  "Latency.h",
  "LayersTypes.h",
  "MediaCache.h",
  "MediaResource.h",
  "MediaSegment.h",
  "MediaStreamGraph.h",
  "mozilla/Assertions.h",
  "mozilla/Attributes.h",
  "mozilla/CDMCaps.h",
  "mozilla/CDMProxy.h",
  "mozilla/dom/TimeRanges.h", # included by TimeUnits for converting TimeIntervals, maybe we can extract conversion into a helper?
  "mozilla/ErrorResult.h", # Used by TimeRanges
  "mozilla/gfx/2D.h",
  "mozilla/gfx/Point.h",
  "mozilla/gfx/Rect.h",
  "mozilla/layers/CompositorTypes.h",
  "mozilla/layers/LayersTypes.h",
  "mozilla/Mutex.h", # Rewrite, or make not depend on BlockingResourceBase.h -> XPCOM.h
  "mozilla/Preferences.h",
  "mozilla/Telemetry.h",
  "nsAString.h",
  "nsAutoPtr.h",
  "nsCharSeparatedTokenizer.h",
  "nsCOMPtr.h",
  "nscore.h",
  "nsDebug.h",
  "nsIMemoryReporter.h",
  "nsIObserver.h",
  "nsISupports.h",
  "nsISupportsImpl.h",
  "nsIThread.h",
  "nsITimer.h",
  "nsMargin.h",
  "nsPoint.h",
  "nsPrintfCString.h",
  "nsRect.h",
  "nsServiceManagerUtils.h",
  "nsSize.h",
  "nsString.h",
  "nsAString.h",
  "nsTArray.h",
  "nsThreadUtils.h",
  "VideoFrameContainer.h",
  "MediaResourceCallback.h",
  "nsIServiceManager.h",
  "nsIChannel.h",
  "nsIURI",
  "nsIPrincipal.h",
  "IMFYCbCrImage.h",
  "Layers.h",
  "gfx2DGlue.h",
  "gfxPrefs.h",
  "mozilla/gfx/gfxVars.h",
  "mozilla/gfx/DeviceManagerDx.h",
  "gfxWindowsPlatform.h",
  "WMFVideoMFTManager.cpp",
  "mozilla/mscom/EnsureMTA.h",
  "nsIGfxInfo.h",
  "DXVA2Manager.cpp",
  "ipc/IPCMessageUtils.h",
  "gfxFallback.h",
  "FrameMetrics.h",
}


terminal_files = {
  # "gfx2DGlue.h",
  # "gfxContext.h",
  "GMPCrashHelper.h",
  "GeckoProfiler.h",
  "ImageContainer.h",
  # "Latency.h",
  # "LayersTypes.h",
  "Layers.h",
  "MediaCache.h",
  "MediaResource.h",
  "nsContentUtils.h",
  # "MediaSegment.h",
  "MediaStreamGraph.h",
  # "mozilla/mozalloc.h",
  "mozilla/Assertions.h",
  "mozilla/CDMCaps.h",
  "mozilla/CDMProxy.h",
  # "mozilla/ErrorResult.h", # Used by TimeRanges
  "mozilla/layers/CompositorTypes.h",
  "mozilla/layers/KnowsCompositor.h",
  "mozilla/layers/LayersTypes.h",
  # "mozilla/Mutex.h", # Rewrite, or make not depend on BlockingResourceBase.h -> XPCOM.h
  "mozilla/Preferences.h",
  "mozilla/Telemetry.h",
  "nsAutoPtr.h",
  # "nsCharSeparatedTokenizer.h",
  "nsCOMPtr.h",
  # "nscore.h",
  # "nsDebug.h",
  # "nsIMemoryReporter.h",
  # "nsIObserver.h",
  # "nsISupports.h",
  "nsIPrincipal.h",
  # "nsISupportsImpl.h",
  "nsIThread.h",
  "nsTArray.h",
  "nsITimer.h",
  "nsTraceRefcnt.h",
  # "nsPrintfCString.h",
  # "nsServiceManagerUtils.h",
  # "nsString.h",
  # "nsAString.h",
  # "nsTArray.h",
  # "nsStringFwd.h",
  "StreamTracks.h",
  # "nsClassHashtable.h",
  # "nsDataHashtable.h",
  # "nsRefPtrHashtable.h",
  # "nsTHashtable.h",

  "nsCycleCollectionNoteChild.h",
  "nsISupportsImpl.h",
  "nsDebug.h",

}


